# Generated by Django 2.1.7 on 2020-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='problems',
            field=models.ManyToManyField(to='problem.Problem'),
        ),
    ]
