# Generated by Django 2.1.7 on 2020-09-01 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0002_collection_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', utils.models.RichTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', utils.models.RichTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(to='problem.Problem')),
            ],
            options={
                'db_table': 'practice',
                'ordering': ('-create_time',),
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='problems',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='course',
            name='practices',
            field=models.ManyToManyField(to='collection.Practice'),
        ),
        migrations.AddField(
            model_name='course',
            name='problems',
            field=models.ManyToManyField(to='problem.Problem'),
        ),
    ]
